### ISSUE TITLE
Error while doing Get operation after doing Set for LDAP settings

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imcsdk#46] opened 2016-10-24 15:45 UTC
Python version: 2.7.12
IMC version: 2.0(13e)

**Observation:**
When trying to validate settings of LDAP by doing get operation after setting one of the parameter "group_nested_search" to some value say '128', it fails because the value of this param shows 'None' and other param [x]groupNestedSearch shows value as '128.

**The following code was executed -**
mo.admin_state = 'enabled'
           mo.attribute = 'CiscoAvPair'
           mo.bind_dn = 'DC=a,DC=b,DC=c'
           mo.bind_method = 'login-credentials'
           mo.encryption = 'enabled'
           mo.filter = 'sAMAccountName'
           mo.group_attribute = 'memberOf'
           mo.group_auth = 'enabled'
           **mo.group_nested_search = '128'**
           mo.ldap_server1 = '10.10.10.10'
           mo.ldap_server_port1 = '3268'
           mo.locate_directory_using_dns = 'no'
           mo.timeout = '60'
           handle.set_mo(mo)

**After doing get operation, the output is -**
## Managed Object                  :       AaaLdap

admin_state                     :enabled
attribute                       :CiscoAvPair
basedn                          :
bind_dn                         :DC=a,DC=b,DC=c
bind_method                     :login-credentials
dn                              :sys/ldap-ext
dns_domain_source               :extracted-domain
dns_search_domain               :
dns_search_forest               :
domain                          :
encryption                      :enabled
filter                          :sAMAccountName
**_[X]groupNestedSearch            :128_**
group_attribute                 :memberOf
group_auth                      :enabled
**group_nested_search             :None**
ldap_server1                    :10.10.10.10
ldap_server2                    :
ldap_server3                    :
ldap_server4                    :
ldap_server5                    :
ldap_server6                    :
ldap_server_port1               :3268
ldap_server_port2               :389
ldap_server_port3               :389
ldap_server_port4               :3268
ldap_server_port5               :3268
ldap_server_port6               :3268
locate_directory_using_dns      :no
password                        :
rn                              :ldap-ext
status                          :None
timeout                         :60

**Comment by waghswapnil** [comment] 2016-10-25 06:23
Root cause and fix identified. Fix has been verified with a private build.

**Comment by waghswapnil** [comment] 2016-11-10 09:51
will be addressed by #49

**Comment by waghswapnil** [comment] 2016-11-19 06:40
fixed by #49

**Closed as completed by waghswapnil** 2016-11-19 06:40 UTC
